---
- name: applying securitygroup rules
  hosts: localhosts
  sudo: yes
  gather_facts: yes
  vars_files:
  - [var.yml]
  tasks:
  - name: ec2 group
    ec2_group:
      name: ec2 group name
      description: an example for ec2 group
      vpc_id: "{{vpc_id}}"
      region: "{{region}}"
      aws_secret_key: "{{aws_secret_key}}"
      aws_access_key: "{{aws_access_key}}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.0.0.0/8
      - proto: udp
        from _port: 10051
        to_port: 10051
        group_id: sg_12345678
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: 10.0.0.0/8
        rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 10.0.0.0/8
        cidr_ipv6: 64:ff9b::/96
