---
 - hosts: localhost
   name: Configuring Inbound/Outbound Rules in Route table for EC2
   connection: localhost
   var_files:
   - [var.yml]
   tasks:
   - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-1245678
        region: us-west-1
        aws_secret_key:  "{{aws_secret_key}}"
        aws_access_key: "{{aws_access_key}}"
        tags:
          Name: Public
        subnets:
          - "{{ vpn_subnet.subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
             gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table